### ISSUE TITLE
ReadME

### ISSUE THREAD

**Issue by Darrenxc** [sachit-menon/pulse#1]
Hi,
your work is amazing, Can you upload some ReadME to help us understand these codes clearly?
thank you

**Comment by sachit-menon** [comment]
Hi, thanks for your comment - sorry for any confusion, we ended up changing repositories to https://github.com/adamian98/pulse (my coauthor's GitHub account) after rewriting the codebase. I'll be putting up a ReadME there shortly (next 1-2 days). I'll take this repo down at that time. Let me know at that time if you have any confusion.
